### ISSUE TITLE
Threat Intelligence module

### ISSUE THREAD

**Issue by seifreed** [PayloadSecurity/VxFAME#6]
I put the vxstream.py under the folder:

<img width="802" alt="screen shot 2017-09-11 at 20 59 13" src="https://user-images.githubusercontent.com/1843119/30291776-2fe03362-9734-11e7-8dd4-58c2037761ef.png">

But the module is not loaded on FAME. I started the workers many times, but never is loaded:

<img width="2243" alt="screen shot 2017-09-11 at 20 59 30" src="https://user-images.githubusercontent.com/1843119/30291815-4eac6748-9734-11e7-8d76-9e99e4d044be.png">

**Comment by diogo-fernan** [comment]
Closing as per #8.
