### ISSUE TITLE
Modules not loaded properly

### ISSUE THREAD

**Issue by gaelmuller** [PayloadSecurity/VxFAME#8]
I looked at the modules and have the following comments:

* The best way to use third party modules in FAME is to add a module repository. In order for this repository to work in this context, it needs an `__init__.py` file at the root.
* When added as a module repository, the `vxstream.py` file will conflict with the `vxstream` package. I would advise renaming the file of moving it to its own directory.
* The Threat Intelligence module is not loaded by FAME because it is trying to import re.fullmatch, which is not available in Python 2.7.

Unrelated question: can these modules be used with a free account on hybrid-analysis.com or do they require a commercial account ?

**Comment by millerjkd** [comment]
Let me take the last question: we plan on opening up the full API to HA quite soon, so that then both modules could be used with a free account. As it is now, only the threat intelligence module would be usable by the restricted API keys.

**Comment by diogo-fernan** [comment]
@gaelmuller this repository is hosting both a processing and an intelligence module. The processing module is already in the form of a package containing a `__init__.py` file at the root.

**Comment by gaelmuller** [comment]
The whole repository needs to be a package. This is why you also need an `__init__.py` file at the root of the repository. You can see that the https://github.com/certsocietegenerale/fame_modules repository has one.

**Comment by diogo-fernan** [comment]
Just pushed a new organization of the module. Is this in line with the required?

**Comment by gaelmuller** [comment]
Perfect. Adding this repository to a FAME instance now loads both modules correctly. This should fixe #6 as well.
